#%Dialect 1.0
uses:
  product_eg: ../../Product/Product/schema.yaml
  contactpoint_eg: ../../Party/ContactPoint/schema.yaml
  salesorder_eg: ../../SalesOrder/SalesOrder/schema.yaml
nodeMappings:
  ShipmentDocument:
    classTerm: cim.ShipmentDocument
    mapping:
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      shipment:
        propertyTerm: cim.shipment
        range: Shipment
        mandatory: true
        allowMultiple: true
  ShipmentPackage:
    classTerm: cim.ShipmentPackage
    mapping:
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      shipmentProductCount:
        propertyTerm: cim.shipmentProductCount
        range: integer
        mandatory: true
      shipmentProductDescription:
        propertyTerm: cim.shipmentProductDescription
        range: string
        mandatory: true
      shipment:
        propertyTerm: cim.shipment
        range: Shipment
        mandatory: true
        allowMultiple: true
  ShippingMethod:
    classTerm: cim.ShippingMethod
    mapping:
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      product:
        propertyTerm: cim.product
        range: product_eg.Product
        mandatory: true
        allowMultiple: true
      name:
        propertyTerm: cim.name
        range: string
        mandatory: true
      description:
        propertyTerm: cim.description
        range: string
        mandatory: true
  ShipmentProduct:
    classTerm: cim.ShipmentProduct
    mapping:
      salesOrderProduct:
        propertyTerm: cim.salesOrderProduct
        range: salesorder_eg.SalesOrderProduct
        mandatory: true
        allowMultiple: true
      product:
        propertyTerm: cim.product
        range: product_eg.Product
        mandatory: true
        allowMultiple: true
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      shipmentPackage:
        propertyTerm: cim.shipmentPackage
        range: ShipmentPackage
        mandatory: true
        allowMultiple: true
      shipment:
        propertyTerm: cim.shipment
        range: Shipment
        mandatory: true
        allowMultiple: true
      shipmentProductCount:
        propertyTerm: cim.shipmentProductCount
        range: integer
        mandatory: true
  Shipment:
    classTerm: cim.Shipment
    mapping:
      shipmentStatus:
        propertyTerm: cim.shipmentStatus
        range: ShipmentStatus
        allowMultiple: true
      salesOrder:
        propertyTerm: cim.salesOrder
        range: salesorder_eg.SalesOrder
        allowMultiple: true
      carrierTrackingNumber:
        propertyTerm: cim.carrierTrackingNumber
        range: string
      salesOrderDeliveryGroup:
        propertyTerm: cim.salesOrderDeliveryGroup
        range: salesorder_eg.SalesOrderDeliveryGroup
        allowMultiple: true
      shipmentDate:
        propertyTerm: cim.shipmentDate
        range: date
        mandatory: true
      specialInstructionsText:
        propertyTerm: cim.specialInstructionsText
        range: string
      giftMessageText:
        propertyTerm: cim.giftMessageText
        range: string
      actualDeliveryDateTime:
        propertyTerm: cim.actualDeliveryDateTime
        range: time
      estimatedDeliveryDateTime:
        propertyTerm: cim.estimatedDeliveryDateTime
        range: time
      isGift:
        propertyTerm: cim.isGift
        range: boolean
      scheduledDeliveryDateTime:
        propertyTerm: cim.scheduledDeliveryDateTime
        range: time
      shipmentNumber:
        propertyTerm: cim.shipmentNumber
        range: string
      shipToAddress:
        propertyTerm: cim.shipToAddress
        range: contactpoint_eg.ContactPointAddress
        allowMultiple: true
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
  ShipmentProductPriceAdjustment:
    classTerm: cim.ShipmentProductPriceAdjustment
    mapping:
      adjustmentTaxAmount:
        propertyTerm: cim.adjustmentTaxAmount
        range: integer
      adjustmentAmount:
        propertyTerm: cim.adjustmentAmount
        range: integer
        mandatory: true
      shipmentProduct:
        propertyTerm: cim.shipmentProduct
        range: ShipmentProduct
        mandatory: true
        allowMultiple: true
      shipmentProductPriceAdjustmentAmount:
        propertyTerm: cim.shipmentProductPriceAdjustmentAmount
        range: integer
      description:
        propertyTerm: cim.description
        range: string
        mandatory: true
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
  ShipmentStatus:
    classTerm: cim.ShipmentStatus
    mapping:
      description:
        propertyTerm: cim.description
        range: string
        mandatory: true
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      name:
        propertyTerm: cim.name
        range: string
        mandatory: true
  ShipmentProductPriceAdjustmentTax:
    classTerm: cim.ShipmentProductPriceAdjustmentTax
    mapping:
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      shipmentProductPriceAdjustment:
        propertyTerm: cim.shipmentProductPriceAdjustment
        range: ShipmentProductPriceAdjustment
        mandatory: true
        allowMultiple: true
      name:
        propertyTerm: cim.name
        range: string
        mandatory: true
external:
  cim: http://cloudinformationmodel.org/model/
dialect: ShipmentEntityGroup
version: "0.1"
documents:
  root:
    declares:
      ShipmentDocumentSchemas: ShipmentDocument
      ShipmentPackageSchemas: ShipmentPackage
      ShippingMethodSchemas: ShippingMethod
      ShipmentProductSchemas: ShipmentProduct
      ShipmentSchemas: Shipment
      ShipmentProductPriceAdjustmentSchemas: ShipmentProductPriceAdjustment
      ShipmentStatusSchemas: ShipmentStatus
      ShipmentProductPriceAdjustmentTaxSchemas: ShipmentProductPriceAdjustmentTax
  fragments:
    encodes:
      ShipmentDocument: ShipmentDocument
      ShipmentPackage: ShipmentPackage
      ShippingMethod: ShippingMethod
      ShipmentProduct: ShipmentProduct
      Shipment: Shipment
      ShipmentProductPriceAdjustment: ShipmentProductPriceAdjustment
      ShipmentStatus: ShipmentStatus
      ShipmentProductPriceAdjustmentTax: ShipmentProductPriceAdjustmentTax