#%Dialect 1.0
uses:
  productattribute_eg: ../ProductAttribute/schema.yaml
  account_eg: ../../Party/Account/schema.yaml
  productcatalog_eg: ../ProductCatalog/schema.yaml
  salesorder_eg: ../../SalesOrder/SalesOrder/schema.yaml
nodeMappings:
  BundleProduct:
    classTerm: cim.BundleProduct
    mapping:
      quantityUnitOfMeasure:
        propertyTerm: cim.quantityUnitOfMeasure
        range: string
      bundledProductsSubstitutional:
        propertyTerm: cim.bundledProductsSubstitutional
        range: boolean
        mandatory: true
      tareWeight:
        propertyTerm: cim.tareWeight
        range: integer
      bundledProductsSoldTogether:
        propertyTerm: cim.bundledProductsSoldTogether
        range: boolean
        mandatory: true
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      expectedWasteCount:
        propertyTerm: cim.expectedWasteCount
        range: integer
      bundledProductsDecidedAtUse:
        propertyTerm: cim.bundledProductsDecidedAtUse
        range: boolean
      quantityCount:
        propertyTerm: cim.quantityCount
        range: integer
      weightUOM:
        propertyTerm: cim.weightUOM
        range: string
      bundledProductsDecidesAvailability:
        propertyTerm: cim.bundledProductsDecidesAvailability
        range: boolean
    extends: Product
  ProductRelatedProduct:
    classTerm: cim.ProductRelatedProduct
    mapping:
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      salesOrderProduct1:
        propertyTerm: cim.salesOrderProduct1
        range: salesorder_eg.SalesOrderProduct
        mandatory: true
        allowMultiple: true
      isDefaultOption:
        propertyTerm: cim.isDefaultOption
        range: boolean
        mandatory: true
      toDate:
        propertyTerm: cim.toDate
        range: date
      fromDate:
        propertyTerm: cim.fromDate
        range: date
        mandatory: true
      name:
        propertyTerm: cim.name
        range: string
        mandatory: true
      childProduct:
        propertyTerm: cim.childProduct
        range: Product
        mandatory: true
        allowMultiple: true
      parentProduct:
        propertyTerm: cim.parentProduct
        range: Product
        mandatory: true
        allowMultiple: true
      salesOrderProduct2:
        propertyTerm: cim.salesOrderProduct2
        range: salesorder_eg.SalesOrderProduct
        mandatory: true
        allowMultiple: true
      productRelationshipType:
        propertyTerm: cim.productRelationshipType
        range: salesorder_eg.ProductRelationshipType
        mandatory: true
        allowMultiple: true
  ProductRelationshipType:
    classTerm: cim.ProductRelationshipType
    mapping:
      parentProductRole:
        propertyTerm: cim.parentProductRole
        range: string
        mandatory: true
      childProductRole:
        propertyTerm: cim.childProductRole
        range: string
        mandatory: true
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      parentProductRole:
        propertyTerm: cim.parentProductRole
        range: string
        mandatory: true
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      childProductRole:
        propertyTerm: cim.childProductRole
        range: string
        mandatory: true
  ProductTranslation:
    classTerm: cim.ProductTranslation
    mapping:
      name:
        propertyTerm: cim.name
        range: string
        mandatory: true
      product:
        propertyTerm: cim.product
        range: Product
        mandatory: true
        allowMultiple: true
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      longDescription:
        propertyTerm: cim.longDescription
        range: string
      description:
        propertyTerm: cim.description
        range: string
  ServiceProduct:
    classTerm: cim.ServiceProduct
    mapping:
      serviceProviderAccount:
        propertyTerm: cim.serviceProviderAccount
        range: account_eg.Account
        allowMultiple: true
      servicePeriodCount:
        propertyTerm: cim.servicePeriodCount
        range: integer
      serviceType:
        propertyTerm: cim.serviceType
        range: string
        mandatory: true
      evergreenContractEstimatedChargeAmount:
        propertyTerm: cim.evergreenContractEstimatedChargeAmount
        range: integer
      evergreenContractEstimatedMonthCount:
        propertyTerm: cim.evergreenContractEstimatedMonthCount
        range: integer
      rentalCleanupFeeAmount:
        propertyTerm: cim.rentalCleanupFeeAmount
        range: integer
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      rentalTermViolationPenaltyAmount:
        propertyTerm: cim.rentalTermViolationPenaltyAmount
        range: integer
      servicePeriodUOM:
        propertyTerm: cim.servicePeriodUOM
        range: string
    extends: Product
  GoodsProduct:
    classTerm: cim.GoodsProduct
    mapping:
      gender:
        propertyTerm: cim.gender
        range: string
      requiredTemperatureLowestNumber:
        propertyTerm: cim.requiredTemperatureLowestNumber
        range: integer
      requiredHumidityPercentage:
        propertyTerm: cim.requiredHumidityPercentage
        range: integer
      diameter:
        propertyTerm: cim.diameter
        range: integer
      productMayExpand:
        propertyTerm: cim.productMayExpand
        range: boolean
        mandatory: true
      requiredCleanupProcess:
        propertyTerm: cim.requiredCleanupProcess
        range: string
      tareWeight:
        propertyTerm: cim.tareWeight
        range: integer
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      color:
        propertyTerm: cim.color
        range: string
      width:
        propertyTerm: cim.width
        range: integer
      requiredTemperatureUOM:
        propertyTerm: cim.requiredTemperatureUOM
        range: string
      sizeUOM:
        propertyTerm: cim.sizeUOM
        range: string
      netWeight:
        propertyTerm: cim.netWeight
        range: integer
      fabric:
        propertyTerm: cim.fabric
        range: string
      season:
        propertyTerm: cim.season
        range: string
      shelfFacingUnitCount:
        propertyTerm: cim.shelfFacingUnitCount
        range: integer
      weightUOM:
        propertyTerm: cim.weightUOM
        range: string
      isMadeToOrder:
        propertyTerm: cim.isMadeToOrder
        range: boolean
        mandatory: true
      productSecurityRequirement:
        propertyTerm: cim.productSecurityRequirement
        range: string
      requiresUnitPriceLabel:
        propertyTerm: cim.requiresUnitPriceLabel
        range: boolean
        mandatory: true
      requiredTemperatureHighestNumber:
        propertyTerm: cim.requiredTemperatureHighestNumber
        range: integer
      maxHoldingDayCount:
        propertyTerm: cim.maxHoldingDayCount
        range: integer
      pattern:
        propertyTerm: cim.pattern
        range: string
      age:
        propertyTerm: cim.age
        range: string
      style:
        propertyTerm: cim.style
        range: string
      drainedWeight:
        propertyTerm: cim.drainedWeight
        range: integer
      height:
        propertyTerm: cim.height
        range: integer
      grossWeight:
        propertyTerm: cim.grossWeight
        range: integer
      isPerishable:
        propertyTerm: cim.isPerishable
        range: boolean
        mandatory: true
      depth:
        propertyTerm: cim.depth
        range: integer
      environmentRequirement:
        propertyTerm: cim.environmentRequirement
        range: string
    extends: Product
  Brand:
    classTerm: cim.Brand
    mapping:
      brandGrade:
        propertyTerm: cim.brandGrade
        range: string
        mandatory: true
      name:
        propertyTerm: cim.name
        range: string
        mandatory: true
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
  ProductImage:
    classTerm: cim.ProductImage
    mapping:
      product:
        propertyTerm: cim.product
        range: Product
        mandatory: true
        allowMultiple: true
      imageViewType:
        propertyTerm: cim.imageViewType
        range: string
      isDefaultImage:
        propertyTerm: cim.isDefaultImage
        range: boolean
        mandatory: true
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
  Product:
    classTerm: cim.Product
    mapping:
      isQuantityEntryRequired:
        propertyTerm: cim.isQuantityEntryRequired
        range: boolean
        mandatory: true
      primarySalesChannel:
        propertyTerm: cim.primarySalesChannel
        range: salesorder_eg.SalesChannel
        allowMultiple: true
      primaryProductCategory:
        propertyTerm: cim.primaryProductCategory
        range: productcatalog_eg.ProductCategory
        allowMultiple: true
      requiresInvididualUnitPricing:
        propertyTerm: cim.requiresInvididualUnitPricing
        range: boolean
        mandatory: true
      quantityScheduleType:
        propertyTerm: cim.quantityScheduleType
        range: string
      isWeightEntryRequired:
        propertyTerm: cim.isWeightEntryRequired
        range: boolean
        mandatory: true
      isMultipleCouponsAllowed:
        propertyTerm: cim.isMultipleCouponsAllowed
        range: boolean
        mandatory: true
      quantityInstallmentCount:
        propertyTerm: cim.quantityInstallmentCount
        range: integer
      isManualPriceEntryRequired:
        propertyTerm: cim.isManualPriceEntryRequired
        range: boolean
        mandatory: true
      isIntellectualPropertyProtected:
        propertyTerm: cim.isIntellectualPropertyProtected
        range: boolean
      brandGrade:
        propertyTerm: cim.brandGrade
        range: string
      standardWarrantyLengthMonth:
        propertyTerm: cim.standardWarrantyLengthMonth
        range: integer
      validForPeriodUOM:
        propertyTerm: cim.validForPeriodUOM
        range: productattribute_eg.ProductValidityTimePeriodUOM
        allowMultiple: true
      isRainCheckAllowed:
        propertyTerm: cim.isRainCheckAllowed
        range: boolean
        mandatory: true
      priceChargeType:
        propertyTerm: cim.priceChargeType
        range: string
        mandatory: true
      revenueInstallmentCount:
        propertyTerm: cim.revenueInstallmentCount
        range: integer
      mSRPAmount:
        propertyTerm: cim.mSRPAmount
        range: integer
      allowPartialRefund:
        propertyTerm: cim.allowPartialRefund
        range: boolean
      requiredDepositAmount:
        propertyTerm: cim.requiredDepositAmount
        range: integer
      type:
        propertyTerm: cim.type
        range: string
      modelYear:
        propertyTerm: cim.modelYear
        range: integer
      modelNumber:
        propertyTerm: cim.modelNumber
        range: string
      isPartnerDiscountAllowed:
        propertyTerm: cim.isPartnerDiscountAllowed
        range: boolean
        mandatory: true
      glAccountCode:
        propertyTerm: cim.glAccountCode
        range: string
      isInstallable:
        propertyTerm: cim.isInstallable
        range: boolean
        mandatory: true
      externalSourceRecord:
        propertyTerm: cim.externalSourceRecord
        range: string
      maximumOrderQuantityCount:
        propertyTerm: cim.maximumOrderQuantityCount
        range: integer
      minimumAdvertisementAmountStartDate:
        propertyTerm: cim.minimumAdvertisementAmountStartDate
        range: integer
      description:
        propertyTerm: cim.description
        range: string
        mandatory: true
      productStatus:
        propertyTerm: cim.productStatus
        range: string
        mandatory: true
      canUseRevenueSchedule:
        propertyTerm: cim.canUseRevenueSchedule
        range: boolean
        mandatory: true
      isReturnable:
        propertyTerm: cim.isReturnable
        range: boolean
        mandatory: true
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      revenueScheduleType:
        propertyTerm: cim.revenueScheduleType
        range: string
      lotIdentifier:
        propertyTerm: cim.lotIdentifier
        range: string
      brand:
        propertyTerm: cim.brand
        range: Brand
        allowMultiple: true
      displayUrl:
        propertyTerm: cim.displayUrl
        range: string
      manufacturerName:
        propertyTerm: cim.manufacturerName
        range: string
      revenueInstallmentPeriod:
        propertyTerm: cim.revenueInstallmentPeriod
        range: string
      rewardProgramPointsCount:
        propertyTerm: cim.rewardProgramPointsCount
        range: integer
      isAutoProvisionable:
        propertyTerm: cim.isAutoProvisionable
        range: boolean
        mandatory: true
      validToDate:
        propertyTerm: cim.validToDate
        range: date
      isPreOrderable:
        propertyTerm: cim.isPreOrderable
        range: boolean
        mandatory: true
      validForPeriodCount:
        propertyTerm: cim.validForPeriodCount
        range: integer
      productSKU:
        propertyTerm: cim.productSKU
        range: string
        mandatory: true
      isDynamicBundle:
        propertyTerm: cim.isDynamicBundle
        range: boolean
        mandatory: true
      isQualityVerificationRequired:
        propertyTerm: cim.isQualityVerificationRequired
        range: boolean
        mandatory: true
      isSellableWithoutPrice:
        propertyTerm: cim.isSellableWithoutPrice
        range: boolean
        mandatory: true
      minimumAdvertisementAmount:
        propertyTerm: cim.minimumAdvertisementAmount
        range: integer
      isSellableIndependently:
        propertyTerm: cim.isSellableIndependently
        range: boolean
        mandatory: true
      allowCustomerReturn:
        propertyTerm: cim.allowCustomerReturn
        range: boolean
      isBackOrdered:
        propertyTerm: cim.isBackOrdered
        range: boolean
        mandatory: true
      isCouponRedemptionAllowed:
        propertyTerm: cim.isCouponRedemptionAllowed
        range: boolean
        mandatory: true
      isWorkerDiscountAllowed:
        propertyTerm: cim.isWorkerDiscountAllowed
        range: boolean
        mandatory: true
      canUseQuantitySchedule:
        propertyTerm: cim.canUseQuantitySchedule
        range: boolean
        mandatory: true
      isSellable:
        propertyTerm: cim.isSellable
        range: boolean
      stockLedgerValuationAmount:
        propertyTerm: cim.stockLedgerValuationAmount
        range: integer
      name:
        propertyTerm: cim.name
        range: string
        mandatory: true
      validFromDate:
        propertyTerm: cim.validFromDate
        range: date
      isFoodstampPaymentAllowed:
        propertyTerm: cim.isFoodstampPaymentAllowed
        range: boolean
        mandatory: true
      quantityInstallmentPeriod:
        propertyTerm: cim.quantityInstallmentPeriod
        range: string
      isCustomerDiscountAllowed:
        propertyTerm: cim.isCustomerDiscountAllowed
        range: boolean
        mandatory: true
      isSerialized:
        propertyTerm: cim.isSerialized
        range: boolean
        mandatory: true
      longDescription:
        propertyTerm: cim.longDescription
        range: string
        mandatory: true
      versionNumber:
        propertyTerm: cim.versionNumber
        range: string
      minimumOrderQuantityCount:
        propertyTerm: cim.minimumOrderQuantityCount
        range: integer
      masterProduct:
        propertyTerm: cim.masterProduct
        range: Product
        allowMultiple: true
      requiredDepositPercentage:
        propertyTerm: cim.requiredDepositPercentage
        range: integer
      disposalType:
        propertyTerm: cim.disposalType
        range: string
  ProductImageTranslation:
    classTerm: cim.ProductImageTranslation
    mapping:
      productImage:
        propertyTerm: cim.productImage
        range: ProductImage
        mandatory: true
        allowMultiple: true
      translatedName:
        propertyTerm: cim.translatedName
        range: string
        mandatory: true
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
external:
  cim: http://cloudinformationmodel.org/model/
dialect: ProductEntityGroup
version: "0.1"
documents:
  root:
    declares:
      BundleProductSchemas: BundleProduct
      ProductRelatedProductSchemas: ProductRelatedProduct
      ProductRelationshipTypeSchemas: ProductRelationshipType
      ProductTranslationSchemas: ProductTranslation
      ServiceProductSchemas: ServiceProduct
      GoodsProductSchemas: GoodsProduct
      BrandSchemas: Brand
      ProductImageSchemas: ProductImage
      ProductSchemas: Product
      ProductImageTranslationSchemas: ProductImageTranslation
  fragments:
    encodes:
      BundleProduct: BundleProduct
      ProductRelatedProduct: ProductRelatedProduct
      ProductRelationshipType: ProductRelationshipType
      ProductTranslation: ProductTranslation
      ServiceProduct: ServiceProduct
      GoodsProduct: GoodsProduct
      Brand: Brand
      ProductImage: ProductImage
      Product: Product
      ProductImageTranslation: ProductImageTranslation