#%Dialect 1.0
uses:
  party_eg: ../Party/schema.yaml
nodeMappings:
  Competitor:
    classTerm: cim.Competitor
    mapping:
      currentRatio:
        propertyTerm: cim.currentRatio
        range: integer
      competitorFromDate:
        propertyTerm: cim.competitorFromDate
        range: date
        mandatory: true
      assetReturnRatio:
        propertyTerm: cim.assetReturnRatio
        range: integer
      competitorToDate:
        propertyTerm: cim.competitorToDate
        range: date
      competitorWeaknesses:
        propertyTerm: cim.competitorWeaknesses
        range: string
      competitorStrengths:
        propertyTerm: cim.competitorStrengths
        range: string
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      pressMentionsRate:
        propertyTerm: cim.pressMentionsRate
        range: integer
      cashFlowGrowth:
        propertyTerm: cim.cashFlowGrowth
        range: integer
      assetTurnoverRatio:
        propertyTerm: cim.assetTurnoverRatio
        range: integer
      socialMediaPostRate:
        propertyTerm: cim.socialMediaPostRate
        range: integer
      adKeywords:
        propertyTerm: cim.adKeywords
        range: string
      ptoENumber:
        propertyTerm: cim.ptoENumber
        range: integer
      adReachRate:
        propertyTerm: cim.adReachRate
        range: integer
      netProfitMargin:
        propertyTerm: cim.netProfitMargin
        range: integer
      competitorLeverageOpportunities:
        propertyTerm: cim.competitorLeverageOpportunities
        range: string
      competitorObjectives:
        propertyTerm: cim.competitorObjectives
        range: string
      competitorThreats:
        propertyTerm: cim.competitorThreats
        range: string
    extends: PartyRole
  PartyRole:
    classTerm: cim.PartyRole
    mapping:
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      party:
        propertyTerm: cim.party
        range: party_eg.Party
        mandatory: true
        allowMultiple: true
  Customer:
    classTerm: cim.Customer
    mapping:
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      totalContractedAmount:
        propertyTerm: cim.totalContractedAmount
        range: integer
      totalLifeTimeValue:
        propertyTerm: cim.totalLifeTimeValue
        range: integer
      marketingEmailResponseRate:
        propertyTerm: cim.marketingEmailResponseRate
        range: integer
      originatingCustomerSource:
        propertyTerm: cim.originatingCustomerSource
        range: string
      totalProfitContributionAmount:
        propertyTerm: cim.totalProfitContributionAmount
        range: integer
      prospectRating:
        propertyTerm: cim.prospectRating
        range: string
      netPromoterScore:
        propertyTerm: cim.netPromoterScore
        range: integer
      last24MonthsNewRevenueAmount:
        propertyTerm: cim.last24MonthsNewRevenueAmount
        range: integer
      last12MonthsSupportCallCount:
        propertyTerm: cim.last12MonthsSupportCallCount
        range: integer
      customerStatus:
        propertyTerm: cim.customerStatus
        range: string
        mandatory: true
      totalBookingsAmount:
        propertyTerm: cim.totalBookingsAmount
        range: integer
      churnScore:
        propertyTerm: cim.churnScore
        range: integer
      customerSatisfactionScore:
        propertyTerm: cim.customerSatisfactionScore
        range: integer
      customerNumber:
        propertyTerm: cim.customerNumber
        range: string
      last12MonthsNewRevenueAmount:
        propertyTerm: cim.last12MonthsNewRevenueAmount
        range: integer
    extends: PartyRole
  Seller:
    classTerm: cim.Seller
    mapping:
      newCustomerAcquisitionCount:
        propertyTerm: cim.newCustomerAcquisitionCount
        range: integer
      successStoryCount:
        propertyTerm: cim.successStoryCount
        range: integer
      marketingDevelopmentAmount:
        propertyTerm: cim.marketingDevelopmentAmount
        range: integer
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      jointBusinessPlanExist:
        propertyTerm: cim.jointBusinessPlanExist
        range: boolean
      averageConvertedLeadAmount:
        propertyTerm: cim.averageConvertedLeadAmount
        range: integer
      documentationDownloadCount:
        propertyTerm: cim.documentationDownloadCount
        range: integer
      systemLoginCount:
        propertyTerm: cim.systemLoginCount
        range: integer
      trialParticipationCount:
        propertyTerm: cim.trialParticipationCount
        range: integer
      opportunityInvolvementCount:
        propertyTerm: cim.opportunityInvolvementCount
        range: integer
      customerSatisfactionScore:
        propertyTerm: cim.customerSatisfactionScore
        range: integer
      satisfactionScore:
        propertyTerm: cim.satisfactionScore
        range: integer
      estimatedPartnerGrossMargin:
        propertyTerm: cim.estimatedPartnerGrossMargin
        range: integer
      productReturnRate:
        propertyTerm: cim.productReturnRate
        range: integer
      sellerType:
        propertyTerm: cim.sellerType
        range: string
      creditRating:
        propertyTerm: cim.creditRating
        range: integer
      salesAmount:
        propertyTerm: cim.salesAmount
        range: integer
      eventParticipationCount:
        propertyTerm: cim.eventParticipationCount
        range: integer
      majorPostSaleSupportNeeded:
        propertyTerm: cim.majorPostSaleSupportNeeded
        range: boolean
      activeFromDate:
        propertyTerm: cim.activeFromDate
        range: date
        mandatory: true
      activeToDate:
        propertyTerm: cim.activeToDate
        range: date
      opportunityWinRate:
        propertyTerm: cim.opportunityWinRate
        range: integer
      communityParticipationCount:
        propertyTerm: cim.communityParticipationCount
        range: integer
      leadGenerationCount:
        propertyTerm: cim.leadGenerationCount
        range: integer
      trainingCertificationCount:
        propertyTerm: cim.trainingCertificationCount
        range: integer
      inventoryValueAmount:
        propertyTerm: cim.inventoryValueAmount
        range: integer
      trainingParticipationCount:
        propertyTerm: cim.trainingParticipationCount
        range: integer
      demonstrationsGivenCount:
        propertyTerm: cim.demonstrationsGivenCount
        range: integer
    extends: PartyRole
  CustomerStatusHistory:
    classTerm: cim.CustomerStatusHistory
    mapping:
      partyRole:
        propertyTerm: cim.partyRole
        range: PartyRole
        mandatory: true
        allowMultiple: true
      startDateTime:
        propertyTerm: cim.startDateTime
        range: time
        mandatory: true
      endDateTIme:
        propertyTerm: cim.endDateTIme
        range: time
        mandatory: true
      partyRoleStatus:
        propertyTerm: cim.partyRoleStatus
        range: string
        mandatory: true
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
  Supplier:
    classTerm: cim.Supplier
    mapping:
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      supplierSpend:
        propertyTerm: cim.supplierSpend
        range: integer
      competitiveProductPriceRank:
        propertyTerm: cim.competitiveProductPriceRank
        range: integer
      activeToDate:
        propertyTerm: cim.activeToDate
        range: date
      satisfactionEthicsRank:
        propertyTerm: cim.satisfactionEthicsRank
        range: integer
      satisfactionTechnicalSupportRank:
        propertyTerm: cim.satisfactionTechnicalSupportRank
        range: integer
      contractWeightPercent:
        propertyTerm: cim.contractWeightPercent
        range: integer
      satisfactionCustomerServiceRank:
        propertyTerm: cim.satisfactionCustomerServiceRank
        range: integer
      competitiveWarrantyRank:
        propertyTerm: cim.competitiveWarrantyRank
        range: integer
      supplierType:
        propertyTerm: cim.supplierType
        range: string
      contractWeightScore:
        propertyTerm: cim.contractWeightScore
        range: integer
      satisfactionWeightScore:
        propertyTerm: cim.satisfactionWeightScore
        range: integer
      contractProductReturnRate:
        propertyTerm: cim.contractProductReturnRate
        range: integer
      competitiveWeightScore:
        propertyTerm: cim.competitiveWeightScore
        range: integer
      contractSourcingCycleDays:
        propertyTerm: cim.contractSourcingCycleDays
        range: integer
      competitiveWeightPercent:
        propertyTerm: cim.competitiveWeightPercent
        range: integer
      competitiveMarketingRank:
        propertyTerm: cim.competitiveMarketingRank
        range: integer
      contractInvoiceAccuracyRate:
        propertyTerm: cim.contractInvoiceAccuracyRate
        range: integer
      contractProductQualityRate:
        propertyTerm: cim.contractProductQualityRate
        range: integer
      supplierScore:
        propertyTerm: cim.supplierScore
        range: integer
      competitiveCostAvoidanceRank:
        propertyTerm: cim.competitiveCostAvoidanceRank
        range: integer
      isCarrier:
        propertyTerm: cim.isCarrier
        range: boolean
      satisfactionWeightPercent:
        propertyTerm: cim.satisfactionWeightPercent
        range: integer
      contractOnTimeDeliveryRate:
        propertyTerm: cim.contractOnTimeDeliveryRate
        range: integer
      contractDeliveryCorrectnessRate:
        propertyTerm: cim.contractDeliveryCorrectnessRate
        range: integer
      contractBudgetCostRate:
        propertyTerm: cim.contractBudgetCostRate
        range: integer
      contractSLAIssueRate:
        propertyTerm: cim.contractSLAIssueRate
        range: integer
      activeFromDate:
        propertyTerm: cim.activeFromDate
        range: date
        mandatory: true
    extends: PartyRole
external:
  cim: http://cloudinformationmodel.org/model/
dialect: PartyRoleEntityGroup
version: "0.1"
documents:
  root:
    declares:
      CompetitorSchemas: Competitor
      PartyRoleSchemas: PartyRole
      CustomerSchemas: Customer
      SellerSchemas: Seller
      CustomerStatusHistorySchemas: CustomerStatusHistory
      SupplierSchemas: Supplier
  fragments:
    encodes:
      Competitor: Competitor
      PartyRole: PartyRole
      Customer: Customer
      Seller: Seller
      CustomerStatusHistory: CustomerStatusHistory
      Supplier: Supplier