#%Dialect 1.0
uses:
  party_eg: ../Party/schema.yaml
nodeMappings:
  ContactPointEmail:
    classTerm: cim.ContactPointEmail
    mapping:
      emailAddress:
        propertyTerm: cim.emailAddress
        range: string
        mandatory: true
      emailLatestBounceReasonText:
        propertyTerm: cim.emailLatestBounceReasonText
        range: string
        mandatory: true
      emailLatestBounceDateTime:
        propertyTerm: cim.emailLatestBounceDateTime
        range: date
        mandatory: true
      emailMailBox:
        propertyTerm: cim.emailMailBox
        range: string
        mandatory: true
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      emailDomain:
        propertyTerm: cim.emailDomain
        range: string
        mandatory: true
    extends: ContactPoint
  ContactPointApp:
    classTerm: cim.ContactPointApp
    mapping:
      applicationLogin:
        propertyTerm: cim.applicationLogin
        range: string
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
    extends: ContactPoint
  PartyWebAddress:
    classTerm: cim.PartyWebAddress
    mapping:
      webSiteURL:
        propertyTerm: cim.webSiteURL
        range: string
        mandatory: true
      party:
        propertyTerm: cim.party
        range: party_eg.Party
        mandatory: true
        allowMultiple: true
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
    extends: ContactPoint
  ContactPointPhone:
    classTerm: cim.ContactPointPhone
    mapping:
      areaCode:
        propertyTerm: cim.areaCode
        range: string
      countryName:
        propertyTerm: cim.countryName
        range: string
      formattedE164PhoneNumber:
        propertyTerm: cim.formattedE164PhoneNumber
        range: string
      telephoneNumber:
        propertyTerm: cim.telephoneNumber
        range: string
        mandatory: true
      shortCode:
        propertyTerm: cim.shortCode
        range: integer
      isSMSCapable:
        propertyTerm: cim.isSMSCapable
        range: boolean
        mandatory: true
      isFaxCapable:
        propertyTerm: cim.isFaxCapable
        range: boolean
        mandatory: true
      phoneCountryCode:
        propertyTerm: cim.phoneCountryCode
        range: string
      primaryPhoneType:
        propertyTerm: cim.primaryPhoneType
        range: string
        mandatory: true
      formattedNationalPhoneNumber:
        propertyTerm: cim.formattedNationalPhoneNumber
        range: string
        mandatory: true
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      formattedInternationalPhoneNumber:
        propertyTerm: cim.formattedInternationalPhoneNumber
        range: string
        mandatory: true
      extensionNumber:
        propertyTerm: cim.extensionNumber
        range: string
    extends: ContactPoint
  ContactPoint:
    classTerm: cim.ContactPoint
    mapping:
      activeToDate:
        propertyTerm: cim.activeToDate
        range: date
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      profileFirstCreatedDate:
        propertyTerm: cim.profileFirstCreatedDate
        range: time
      activeFromDate:
        propertyTerm: cim.activeFromDate
        range: date
        mandatory: true
      bestTimeToContactStartTime:
        propertyTerm: cim.bestTimeToContactStartTime
        range: time
      forBusinessUse:
        propertyTerm: cim.forBusinessUse
        range: boolean
        mandatory: true
      primaryFlag:
        propertyTerm: cim.primaryFlag
        range: boolean
      bestTimeToContactEndTime:
        propertyTerm: cim.bestTimeToContactEndTime
        range: time
      profileLastUpdatedDate:
        propertyTerm: cim.profileLastUpdatedDate
        range: time
      contactPointType:
        propertyTerm: cim.contactPointType
        range: ContactPointType
        mandatory: true
        allowMultiple: true
      forPersonalUse:
        propertyTerm: cim.forPersonalUse
        range: boolean
        mandatory: true
      partyRole:
        propertyTerm: cim.partyRole
        range: string
      party:
        propertyTerm: cim.party
        range: party_eg.Party
        mandatory: true
        allowMultiple: true
      profileOccurrenceCount:
        propertyTerm: cim.profileOccurrenceCount
        range: integer
  ContactPointSocial:
    classTerm: cim.ContactPointSocial
    mapping:
      socialFanStatus:
        propertyTerm: cim.socialFanStatus
        range: string
        mandatory: true
      profilePictureURL:
        propertyTerm: cim.profilePictureURL
        range: string
        mandatory: true
      followersCount:
        propertyTerm: cim.followersCount
        range: integer
        mandatory: true
      socialNetworkProvider:
        propertyTerm: cim.socialNetworkProvider
        range: string
        mandatory: true
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      socialHandle:
        propertyTerm: cim.socialHandle
        range: string
        mandatory: true
      socialHandleName:
        propertyTerm: cim.socialHandleName
        range: string
        mandatory: true
    extends: ContactPoint
  ContactPointType:
    classTerm: cim.ContactPointType
    mapping:
      optInPriority:
        propertyTerm: cim.optInPriority
        range: integer
        mandatory: true
      name:
        propertyTerm: cim.name
        range: string
        mandatory: true
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
  ContactPointLocation:
    classTerm: cim.ContactPointLocation
    mapping:
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
    extends: ContactPoint
  ContactPointAddress:
    classTerm: cim.ContactPointAddress
    mapping:
      addressLine2:
        propertyTerm: cim.addressLine2
        range: string
      geoLatitude:
        propertyTerm: cim.geoLatitude
        range: integer
      addressLine1:
        propertyTerm: cim.addressLine1
        range: string
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      cityName:
        propertyTerm: cim.cityName
        range: string
      isUsedForBilling:
        propertyTerm: cim.isUsedForBilling
        range: boolean
      geoAccuracy:
        propertyTerm: cim.geoAccuracy
        range: integer
      postalCodeText:
        propertyTerm: cim.postalCodeText
        range: string
      countryName:
        propertyTerm: cim.countryName
        range: string
      addressLine4:
        propertyTerm: cim.addressLine4
        range: string
      stateProvinceName:
        propertyTerm: cim.stateProvinceName
        range: string
      addressLine3:
        propertyTerm: cim.addressLine3
        range: string
      isUsedForShipping:
        propertyTerm: cim.isUsedForShipping
        range: boolean
      contactPhone:
        propertyTerm: cim.contactPhone
        range: ContactPointPhone
        allowMultiple: true
      geoLongitude:
        propertyTerm: cim.geoLongitude
        range: integer
    extends: ContactPoint
external:
  cim: http://cloudinformationmodel.org/model/
dialect: ContactPointEntityGroup
version: "0.1"
documents:
  root:
    declares:
      ContactPointEmailSchemas: ContactPointEmail
      ContactPointAppSchemas: ContactPointApp
      PartyWebAddressSchemas: PartyWebAddress
      ContactPointPhoneSchemas: ContactPointPhone
      ContactPointSchemas: ContactPoint
      ContactPointSocialSchemas: ContactPointSocial
      ContactPointTypeSchemas: ContactPointType
      ContactPointLocationSchemas: ContactPointLocation
      ContactPointAddressSchemas: ContactPointAddress
  fragments:
    encodes:
      ContactPointEmail: ContactPointEmail
      ContactPointApp: ContactPointApp
      PartyWebAddress: PartyWebAddress
      ContactPointPhone: ContactPointPhone
      ContactPoint: ContactPoint
      ContactPointSocial: ContactPointSocial
      ContactPointType: ContactPointType
      ContactPointLocation: ContactPointLocation
      ContactPointAddress: ContactPointAddress