#%Dialect 1.0
uses:
  account_eg: ../../Party/Account/schema.yaml
  party_eg: ../../Party/Party/schema.yaml
nodeMappings:
  PaymentMethod:
    classTerm: cim.PaymentMethod
    mapping:
      paymentMethodStatus:
        propertyTerm: cim.paymentMethodStatus
        range: string
        mandatory: true
      paymentMethodType:
        propertyTerm: cim.paymentMethodType
        range: PaymentMethodType
        mandatory: true
        allowMultiple: true
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
  PaymentCard:
    classTerm: cim.PaymentCard
    mapping:
      cardHolderName:
        propertyTerm: cim.cardHolderName
        range: string
        mandatory: true
      companyName:
        propertyTerm: cim.companyName
        range: string
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      cardToken:
        propertyTerm: cim.cardToken
        range: string
        mandatory: true
      billToFirstName:
        propertyTerm: cim.billToFirstName
        range: string
      billToCity:
        propertyTerm: cim.billToCity
        range: string
      creditCardExpired:
        propertyTerm: cim.creditCardExpired
        range: boolean
        mandatory: true
      billToStreet2:
        propertyTerm: cim.billToStreet2
        range: string
      expirationMonth:
        propertyTerm: cim.expirationMonth
        range: string
        mandatory: true
      billToStreet:
        propertyTerm: cim.billToStreet
        range: string
      maskedNumber:
        propertyTerm: cim.maskedNumber
        range: string
        mandatory: true
      name:
        propertyTerm: cim.name
        range: string
        mandatory: true
      billToLastName:
        propertyTerm: cim.billToLastName
        range: string
      expirationYear:
        propertyTerm: cim.expirationYear
        range: string
        mandatory: true
      derivedCardTypeCode:
        propertyTerm: cim.derivedCardTypeCode
        range: string
      paymentCardType:
        propertyTerm: cim.paymentCardType
        range: string
        mandatory: true
      issueNumber:
        propertyTerm: cim.issueNumber
        range: string
        mandatory: true
      numberLastDigits:
        propertyTerm: cim.numberLastDigits
        range: string
        mandatory: true
    extends: PaymentMethod
  PaymentMethodType:
    classTerm: cim.PaymentMethodType
    mapping:
      useMinimumAgeYear:
        propertyTerm: cim.useMinimumAgeYear
        range: integer
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      typeDescription:
        propertyTerm: cim.typeDescription
        range: string
      maxPerPeriodTransactionCount:
        propertyTerm: cim.maxPerPeriodTransactionCount
        range: integer
      mediaType:
        propertyTerm: cim.mediaType
        range: string
      maxPerPeriodAmount:
        propertyTerm: cim.maxPerPeriodAmount
        range: integer
      maxTransactionAmount:
        propertyTerm: cim.maxTransactionAmount
        range: integer
      name:
        propertyTerm: cim.name
        range: string
      typeRequiredIdentification:
        propertyTerm: cim.typeRequiredIdentification
        range: string
  CreditTender:
    classTerm: cim.CreditTender
    mapping:
      account:
        propertyTerm: cim.account
        range: account_eg.Account
        allowMultiple: true
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
    extends: PaymentMethod
  Coupon:
    classTerm: cim.Coupon
    mapping:
      manufacturer:
        propertyTerm: cim.manufacturer
        range: party_eg.Party
        allowMultiple: true
      returnCouponReason:
        propertyTerm: cim.returnCouponReason
        range: string
      isReturnCoupon:
        propertyTerm: cim.isReturnCoupon
        range: boolean
      discountAmount:
        propertyTerm: cim.discountAmount
        range: integer
      secondaryScanCodeLabel:
        propertyTerm: cim.secondaryScanCodeLabel
        range: string
      couponCount:
        propertyTerm: cim.couponCount
        range: integer
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      primaryScanCodeLabel:
        propertyTerm: cim.primaryScanCodeLabel
        range: string
      discountPercentage:
        propertyTerm: cim.discountPercentage
        range: integer
      scanCode:
        propertyTerm: cim.scanCode
        range: string
      isValid:
        propertyTerm: cim.isValid
        range: boolean
      expirationDate:
        propertyTerm: cim.expirationDate
        range: date
      couponStatus:
        propertyTerm: cim.couponStatus
        range: string
      couponCode:
        propertyTerm: cim.couponCode
        range: string
    extends: PaymentMethod
external:
  cim: http://cloudinformationmodel.org/model/
dialect: PaymentMethodEntityGroup
version: "0.1"
documents:
  root:
    declares:
      PaymentMethodSchemas: PaymentMethod
      PaymentCardSchemas: PaymentCard
      PaymentMethodTypeSchemas: PaymentMethodType
      CreditTenderSchemas: CreditTender
      CouponSchemas: Coupon
  fragments:
    encodes:
      PaymentMethod: PaymentMethod
      PaymentCard: PaymentCard
      PaymentMethodType: PaymentMethodType
      CreditTender: CreditTender
      Coupon: Coupon